#!/bin/bash

URL="http://jablan.cloud.dreamfactory.com/rest/system/user?app_name=admin"
ITERATIONS=50 
CONCURRENT=4
VERBOSITY=""
HEADERS='-H "Connection: close" -H "Cache-Control: no-cache" -H "Content-Type: application/json"'
COOKIE="Cookie: "

if [ "$1" != "" ] ; then
	COOKIE="PHPSESSID=${1}"
fi

ab -n ${ITERATIONS} -c ${CONCURRENT} ${VERBOSITY} \
    -H "Cookie: ${COOKIE}" \
    -H "Connection: close" \
    -H "Cache-Control: no-cache" \
    -H "Content-Type: application/json" \
    ${URL}
