<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir . '/.manifest';

return array(
    'DreamFactory\\Tools\\Composer\\' => array($vendorDir . '/dreamfactory/package-installer/src'),
    'DreamFactory\\JetPack\\Examples\\CustomTrigger\\' => array($vendorDir . '/dreamfactory/jetpack-custom-trigger/src'),
);
