<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir . '/.manifest';

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
    'Kisma' => array($vendorDir . '/kisma/kisma/src'),
);
