<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir . '/.manifest';

return array(
    $vendorDir . '/kisma/kisma/src/autoload.php',
    $vendorDir . '/dreamfactory/jetpack-custom-trigger/autoload.php',
);
